import os
import re
import datetime

wiki_dir = r"d:\World-Forge\wiki\LSE"
template_file = r"d:\World-Forge\templates\Janitor_Script_Appendix_Template.js"
export_js = r"d:\World-Forge\Export\LSE_Global\LSE_Global_Appendix.js"

def parse_markdown():
    entries = []
    # Read files in sorted order
    for filename in sorted(os.listdir(wiki_dir)):
        if filename.endswith(".md"):
            with open(os.path.join(wiki_dir, filename), 'r', encoding='utf-8') as f:
                content = f.read()
                
            # Split into sections by H2 or H3 headers
            # A simple regex to find ## or ### followed by space and the title
            sections = re.split(r'\n#{2,3}\s+', content)
            for section in sections[1:]:
                lines = section.strip().split('\n')
                if not lines: continue
                title = lines[0].strip('#').strip()
                body = '\n'.join(lines[1:]).strip()
                if not title or not body: continue
                
                entry_type = "CONCEPT"
                if 'Location' in title or 'Region' in title: entry_type = "LOCATION"
                elif 'Faction' in title or 'House' in title: entry_type = "FACTION"
                
                entries.append((title, entry_type, body, filename))
    return entries

def generate_js(entries):
    with open(template_file, 'r', encoding='utf-8') as f:
        template = f.read()
    
    # We will inject our entries at the bottom of the template.
    footer_idx = template.rfind('];')
    if footer_idx == -1:
        print("Error: Could not find ]; in template")
        return
        
    base_js = template[:footer_idx]
    
    wiki_js = "\n\t// =========================================================================\n\t// AUTOGENERATED WIKI ENTRIES (SYNCED FROM LSE WIKI)\n\t// =========================================================================\n"
    
    for idx, (title, etype, body, src) in enumerate(entries):
        # Clean quotes and backticks to avoid JS syntax errors
        safe_body = body.replace('`', '\\`')
        safe_title = title.lower().replace("'", "\\'")
        
        wiki_js += f"""
	{{
		keywords: ['{safe_title}'],
		priority: 4,
		triggers: ["wiki_auto_{idx}"],
	}},
	{{
		tag: "wiki_auto_{idx}",
		priority: 5,
		scenario: ` [WIKI - {etype}: **{title}**\\n\\n{safe_body}]`
	}},
"""
    wiki_js += "];\n"
    
    final_js = base_js + wiki_js
    
    version_str = datetime.datetime.now().strftime("%Y.%m.%d")
    final_js = final_js.replace("[[WF_INJECT: LOREBOOK NAME]]", "LSE Global Appendix")
    final_js = final_js.replace("[[WF_INJECT: VERSION (UPDATE BASED ON MINOR/MAJOR RELEASE)]]", version_str)
    
    with open(export_js, 'w', encoding='utf-8') as f:
        f.write(final_js)
    print(f"Updated {export_js} with {len(entries)} entries.")

if __name__ == "__main__":
    entries = parse_markdown()
    generate_js(entries)
    print("Wiki Sync Complete.")
